# Generated by Django 5.2.7 on 2026-04-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuctionSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
